create sequence hibernate_sequence start with 1 increment by 1;
create table filmes (id integer generated by default as identity, diretor varchar(255), nome varchar(255), primary key (id));
create table series (id integer generated by default as identity, nome varchar(255), principal varchar(255), primary key (id));
